[project]
name = "commons"
version = "0.1.0"
description = "Implementation of common functionality, enums and interfaces for multiple CRS modules"
authors = [{ name = "George-Andrei Iosif", email = "hi@iosifache.me" }]
requires-python = ">=3.10,<4"
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "pwntools>=4.10.0,<5",
    "docker>=6.1.2,<7",
]

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
